### ISSUE TITLE
Sección Ajustes: MPs

### ISSUE THREAD

**Issue by Br4ssman** [elsemieni/rpgmakeres-core#9]
Esta es una idea a posteriori de la [0.2](https://github.com/elsemieni/rpgmakeres-core/milestone/1).
¿Sería interesante que los usuarios pudiesen contactar entre sí a través de mensajes privados?
¿O interesa que, tal y como se muestra en la información del usuario se contacten y sigan en servicios externos como twitter y otras redes?

Esto planeta varias cuestiones, como el hecho de notificar N mensajes mediante un círculo llamativo y el nº en ajustes (desde el menú) y también quizás desde el propio perfil de usuario.

**Comment by fdelapena** [comment]
El tema de los mensajes privados era interesante en los foros pero tiene implicaciones de privacidad hoy en día que en otros tiempos no era algo de lo que hubiera que preocuparse demasiado. Creo que para eso son más efectivos los datos de correo, perfiles de chats y demás redes.

**Comment by Br4ssman** [comment]
Vale,de base no lo incluí en la plantilla por dudas a esto que acabas de comentar.

También ya tenía la duda de precisamente eso, damos espacio para enlazar con otras redes y por ahí pueden contactarse y seguirse todo lo que quieran.

Lo cierro por el momento hasta si hubiese nueva orden.

Gracias.
